### ISSUE TITLE
Make "X-Forwarded-For" header optional

### ISSUE THREAD

**Issue by beihaifeiwu** [hertz-contrib/reverseproxy#11]
**Is your feature request related to a problem? Please describe.**

the server backend is a gateway service which do not like the X-Forwarded-For header

**Describe the solution you'd like**

Make "X-Forwarded-For" header optional, and configurable

**Comment by FGYFFFF** [comment]
@beihaifeiwu This is a good idea, would you like to contribute to this feature?

**Comment by Skyenought** [comment]
@beihaifeiwu 你的需求具体是什么样的, 我这里提出了一个 PR 这是你的需求吗?

**Comment by li-jin-gou** [comment]
It's been too long since I've had a reply, so I've chosen to close it.
